version: '3.4'
services:
  lydia_api:
    image: "lydia-web-app-server"
    build: 
      context: server/
    env_file:
      - server/.env
    ports:
      - "5000:5000"
    networks:
      main_net:
        ipv4_address: 172.28.1.1
    healthcheck:
      interval: 10s
      retries: 5
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/"]
      timeout: 5s
    restart: on-failure
    entrypoint: 
        - python3
        - lydia_api/app.py
        - --port 5000


  web:
    image: "lydia-web-app-client"
    depends_on:
      - lydia_api
    environment:
        - PORT=3000
        - REACT_APP_API_ENDPOINT=:5000/api/
    build:
      context: client/
    networks:
      main_net:
        ipv4_address: 172.28.1.3
    ports:
    - "3000:3000"
    entrypoint:
      - yarn
      - start

networks:
  main_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
